import { TYPE_DONE, TYPE_ERROR } from '../utils';

export const CHANNEL_TYPES = {
    SET_PAGE: 'channel/SET_PAGE',

    GET_CHANNELS: 'channel/GET_CHANNELS',
    GET_CHANNELS_DONE: TYPE_DONE('channel/GET_CHANNELS'),
    GET_CHANNELS_ERROR: TYPE_ERROR('channel/GET_CHANNELS'),

    GET_CHANNEL: 'channel/GET_CHANNEL',
    GET_CHANNEL_DONE: TYPE_DONE('channel/GET_CHANNEL'),
    GET_CHANNEL_ERROR: TYPE_ERROR('channel/GET_CHANNEL'),

    GET_CHANNEL_VIDEOS: 'channel/GET_CHANNEL_VIDEOS',
    GET_CHANNEL_VIDEOS_DONE: TYPE_DONE('channel/GET_CHANNEL_VIDEOS'),
    GET_CHANNEL_VIDEOS_ERROR: TYPE_ERROR('channel/GET_CHANNEL_VIDEOS'),

    GET_CHANNEL_STATISTICS: 'channel/GET_CHANNEL_STATISTICS',
    GET_CHANNEL_STATISTICS_DONE: TYPE_DONE('channel/GET_CHANNEL_STATISTICS'),
    GET_CHANNEL_STATISTICS_ERROR: TYPE_ERROR('channel/GET_CHANNEL_STATISTICS'),
};
