myNextApplication:
    component: '@sls-next/serverless-component@latest'
    name: 'mediastock-client'
    inputs:
        bucketName: 'mediastock-client'
        publicDirectoryCache:
            value: public, max-age=604800
            test: /\.(gif|jpe?g|png|txt|xml)$/i
