import { TYPE_DONE, TYPE_ERROR } from '../utils';

export const ARTICLE_TYPES = {
    RESET: 'article/RESET',
    SET_PAGE: 'article/SET_PAGE',
    SET_STATE: 'article/SET_STATE',

    GET_ARTICLES: 'article/GET_ARTICLES',
    GET_ARTICLES_DONE: TYPE_DONE('article/GET_ARTICLES'),
    GET_ARTICLES_ERROR: TYPE_ERROR('article/GET_ARTICLES'),

    GET_ARTICLE: 'article/GET_ARTICLE',
    GET_ARTICLE_DONE: TYPE_DONE('article/GET_ARTICLE'),
    GET_ARTICLE_ERROR: TYPE_ERROR('article/GET_ARTICLE'),

    CREATE_ARTICLE: 'article/CREATE_ARTICLE',
    CREATE_ARTICLE_DONE: TYPE_DONE('article/CREATE_ARTICLE'),
    CREATE_ARTICLE_ERROR: TYPE_ERROR('article/CREATE_ARTICLE'),
};
